import { Montserrat } from "next/font/google"
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Gloria Okegbemi | Frontend 3ngineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-200 text-gray-800 page bg-cover bg-no-repeat  relative ${montserrat.variable} antialiased page`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
